export const LOAD_COTATION = 'LOAD_COTATION';
export const SELECT_CURRENCY = 'SELECT_CURRENCY';
export const SELECT_TIME_INTERVAL = 'SELECT_TIME_INTERVAL';
export const SELECT_MAX_COTATION  = 'SELECT_MAX_COTATION';
